main: net.tfminecraft.ArmourShop.ArmourShop
api-version: 1.20
name: ArmourShop
version: 1.0
author: Drefvelin

depend: [TLibs, ItemsAdder, LoneLibs]

commands:
  armourshop:
      useage: /<command>
      description: ArmourShop Command