main: net.tfminecraft.ArmourShop.ArmourShop
api-version: 1.20
name: ArmourShop
version: 1.0
author: Drefvelin

depend: [TLibs, ItemsAdder]
softdepend: [MMOItems, MythicLib]

commands:
  armourshop:
      useage: /<command>
      description: ArmourShop Command